version: '3.1'
services:
  frontend:
    container_name: temperaturas-frontend
    image: masalinas/temperaturas_frontend
    restart: always
    ports:
      - 80:3000
    depends_on:
      - backend
  backend:
    container_name: temperaturas-backend
    image: masalinas/temperaturas_backend
    restart: always
